version: '3.8'
services:
    php-apache-environment:
        container_name: reticula
        build:
            context: ./src
            dockerfile: DockerFile
        depends_on:
            - db
        volumes:
            - ./src:/var/www/html/
        ports:
            - 6060:80
    db:
      container_name: db
      image: mysql
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: "1234" 
          MYSQL_DATABASE: "reticulaisc"
          MYSQL_USER: "usernew"
          MYSQL_PASSWORD: " "
      ports:
          - "3307:3306"